### ISSUE TITLE
(TX) Design a smaller equivalent to the signal generator for the transistors operating frequencies.

### ISSUE THREAD

**Issue by MichaelKi42** [FarmBoy522/CapstonePDr.Brown#4]
•	Requirements: able to produce required frequency for transducer 500kHz, able to produce required frequency for transducer 50kHz, able to switch between the two frequencies, Able to adjust the amplitude of the signal (if required)
Transmitter output: pulse 500V, 2microseconds. (Similar system) or
Excitation: HV 1000v at 5us, LV 600v at 5us (data sheet)

**Comment by FarmBoy522** [comment]
This has mostly been completed by Michael - Will verify with him after completion of component testing. 

The RP2040 will be programmed to pulse at the proper width to control the overall signal generation.
