### ISSUE TITLE
(RX) Design a smaller equivalent to the oscilloscope for the transistors operating frequencies.

### ISSUE THREAD

**Issue by MichaelKi42** [FarmBoy522/CapstonePDr.Brown#5]
•	Requirements: able to receive required frequency for transducer 500kHz, able to receive required frequency for transducer 50kHz, able to switch between the two frequencies, Amplifier to boost amplitude of signal. (If required)

**Comment by FarmBoy522** [comment]
Updating this issue with notes:

- An applicable chip to use would be the AnalogDevices AD9655
- Would need a chip to interface with the differential signaling to logic level
- Would be possible to make smaller by using ICs

**Comment by FarmBoy522** [comment]
Closing this issue as we have decided to use a prebuilt Oscilloscope instead of designing a replacement circuit.
